### PR TITLE
Allow more options for boolean typed variables

### PR DESCRIPTION
**Pull request by stuart-c**
Signed-off-by: Stuart Clark stuart.clark@Jahingo.com

### CODE REVIEW

**Comment by chilts** [comment]
Hiya,

This looks like a good idea. Many thanks.

Would it be possible to write a couple of small tests for it please. Also, I think you have an extra `'` (single quote) in the wrong place at the end of the `valid.boolean` section - see the start of the red highlight.

2016-07-14-094738_306x425_scrot

I'll merge once those bits have been fixed up. :)

Cheers,
Andy

**Comment by stuart-c** [comment]
Oops. That's now fixed & I've added some unit tests.

**Comment by chilts** [comment]
Excellent thanks.

I see you added the booleans `true` and `false` to the valid list. Can you even do that with hash keys (in ES5)? When checking if it is valid, won't that also then try and call `.toLowerCase()` on the boolean? Not sure we need them in there, since I think we're expecting that the value is always a string, and it might be good to keep it that way. What do you think?

**Comment by stuart-c** [comment]
The reason I added them was more for the defaults. But I don't mind either way if you thing they should be left out?

**Comment by chilts** [comment]
I think so. Happy to re-evaluate later but merge this without them this time. :)

**Comment by stuart-c** [comment]
Updated as requested

**Comment by chilts** [comment]
Many thanks! Released to npm as v1.2.0. :)

I've added you to the `package.json` contributors section. Happy to take it out (or amend it) if you like.

**Pull request merged**
